{
  "name": "All-Tests",
  "on": [
    "push",
    "pull_request"
  ],
  "jobs": {
    "build": {
      "strategy": {
        "matrix": {
          "os": [
            "macos-11",
            "windows-latest",
            "ubuntu-latest"
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Install Dependencies",
          "if": "matrix.os == 'ubuntu-latest'",
          "env": {
            "DEBIAN_FRONTEND": "noninteractive"
          },
          "run": "sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential pkg-config libasound2-dev"
        },
        {
          "name": "Stable",
          "run": "cargo test"
        },
        {
          "name": "Clippy",
          "if": "matrix.os == 'ubuntu-latest'",
          "run": "rustup component add clippy\ncargo clippy --all-targets\n"
        }
      ]
    }
  }
}
