{
  "on": [
    "push",
    "pull_request"
  ],
  "name": "All",
  "jobs": {
    "lints": {
      "name": "Lints",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout sources",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Install Dependencies",
          "env": {
            "DEBIAN_FRONTEND": "noninteractive"
          },
          "run": "apt-get update && apt-get install --no-install-recommends -y build-essential pkg-config libasound2-dev"
        },
        {
          "name": "Install stable toolchain",
          "uses": "actions-rs/toolchain@v1",
          "with": {
            "profile": "minimal",
            "toolchain": "stable",
            "override": true,
            "components": "rustfmt, clippy"
          }
        },
        {
          "name": "Run cargo clippy",
          "uses": "actions-rs/cargo@v1",
          "with": {
            "command": "clippy",
            "args": "-- -D warnings"
          }
        }
      ]
    },
    "build": {
      "name": "Build",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "Checkout sources",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "Install Dependencies",
          "env": {
            "DEBIAN_FRONTEND": "noninteractive"
          },
          "run": "apt-get update && apt-get install --no-install-recommends -y build-essential pkg-config libasound2-dev"
        },
        {
          "name": "Install stable toolchain",
          "uses": "actions-rs/toolchain@v1",
          "with": {
            "profile": "minimal",
            "toolchain": "stable",
            "override": true
          }
        },
        {
          "name": "Run cargo build",
          "uses": "actions-rs/cargo@v1",
          "with": {
            "command": "build",
            "args": "--release --locked"
          }
        }
      ]
    }
  }
}
